macos_option_as_alt both

# --- Font Configuration ---
# font_family      JetBrainsMono Nerd Font
font_family      BlexMono Nerd Font Mono
font_size        13.0

# --- Cursor Behavior ---
cursor           none
cursor_blink_interval 0

# --- Midnight Theme ---
include mytheme.conf

# --- Performance & Settings ---
