################################### general ####################################
foreground            #cdd6f4
background            #1e1e2e
selection_foreground  #cdd6f4
selection_background  #45475a
url_color             #cba6f7
cursor                none
################################ window borders ################################
active_border_color   #9399b2
inactive_border_color #313244
bell_border_color     #fab387
################################# tab titlebar #################################
active_tab_foreground   #1e1e2e
active_tab_background   #b4befe
inactive_tab_foreground #7f849c
inactive_tab_background #1e1e2e
############################# terminal 16-palette ##############################
# default version
color0  #181825
color1  #f38ba8
color2  #a6e3a1
color3  #f9e2af
color4  #89b4fa
color5  #cba6f7
color6  #74c7ec
color7  #bac2de
# bright version
color8  #45475a
color9  #eba0ac
color10 #94e2d5
color11 #f5e0dc
color12 #b4befe
color13 #f5c2e7
color14 #89dceb
color15 #cdd6f4
