icons_format = "{icon}"

[theme]
theme = "native"
# [theme.overrides]
# idle_bg = "#123456"
# idle_fg = "#abcdef"

[icons]
icons = "awesome4"
[icons.overrides]
bat = ["|E|", "|_|", "|=|", "|F|"]
bat_charging = "|^| "

[[block]]
block = "cpu"
info_cpu = 20
warning_cpu = 50
critical_cpu = 90

[[block]]
block = "disk_space"
path = "/"
info_type = "available"
alert_unit = "GB"
interval = 20
warning = 20.0
alert = 10.0
format = " $icon available / $available.eng(w:2) "

[[block]]
block = "memory"
format = " $icon $mem_total_used_percents.eng(w:2) "
format_alt = " $icon_swap $swap_used_percents.eng(w:2) "

[[block]]
block = "sound"
[[block.click]]
button = "left"
cmd = "pavucontrol"

[[block]]
block = "net"
format = " $icon $device $graph_down $speed_down -- $graph_up $speed_up "
device = "enp42s0"

[[block]]
block = "time"
interval = 1
format = " $timestamp.datetime(f:'%A %d %B %Y %I:%M:%S %p %Z') "
[[block.click]]
button = "left"
cmd = "~/.config/i3status-rust/cal.sh"

