#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d main social [3] [4] [5] [6] [7] [8] gaming null 

bspc config border_width         2
bspc config window_gap           8

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# autostarts

sxhkd &
picom --config $HOME/.config/picom/picom.conf &
nitrogen --restore &
dunst &
polybar &

bspc rule -a spectacle state=floating
